// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schaken.DAL;

namespace Schaken.Migrations
{
    [DbContext(typeof(SchakenContext))]
    partial class SchakenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Schaken.Models.Partij", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dag")
                        .HasColumnType("int");

                    b.Property<int>("SpelerId")
                        .HasColumnType("int");

                    b.Property<int>("Uitslag")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpelerId");

                    b.ToTable("Partij");
                });

            modelBuilder.Entity("Schaken.Models.Speler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Speler");
                });

            modelBuilder.Entity("Schaken.Models.Partij", b =>
                {
                    b.HasOne("Schaken.Models.Speler", "Speler")
                        .WithMany("Partijen")
                        .HasForeignKey("SpelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speler");
                });

            modelBuilder.Entity("Schaken.Models.Speler", b =>
                {
                    b.Navigation("Partijen");
                });
#pragma warning restore 612, 618
        }
    }
}
